# enable color support of ls and also add handy aliases
    alias ls='ls --color=auto'
    alias ll='ls -l'
    alias lr='ls -lart'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'
alias gitco='git checkout'
alias gitci='git commit'
alias gor='git push origin'
alias gits='git status'
alias gb='git branch'
